allowBuilds:
  better-sqlite3: true
  esbuild: true
  rolldown: true
  sharp: true
  '@parcel/watcher': false
  puppeteer: false
  vue-demi: false
minimumReleaseAgeExclude:
  - nuxt@4.5.1
  - '@nuxt/kit@4.5.1'
  - '@nuxt/nitro-server@4.5.1'
  - '@nuxt/schema@4.5.1'
  - '@nuxt/vite-builder@4.5.1'
